Add project for review 1.0
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #1
Opened 2023-01-13 13:33 UTC by kimfom01

2023-01-15 22:35 UTC, TheCSharpAcademy requested changes

2023-01-15 22:35 UTC, TheCSharpAcademy commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
Please add random numbers from 1 to 10 so each game is different. 

I'll tell you in advance that the logic for division needs to have random number 1 to 100 and the result needs to be a full number. (I'll add that to the requirements).

2023-01-15 22:55 UTC, kimfom01 commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
yeah I think this is better than hard coding the questions. I will work on that. I think this will require me to have a calculator class to perform the calculations and validate the answers. not gonna lie I started out this way but scrapped it because I thought hard coding the questions was an easier approach 😂😂

2023-01-15 23:55 UTC, kimfom01 commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
Hmmm I think I need to think this one through 🤣

2023-01-16 20:19 UTC, TheCSharpAcademy commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
@kimfom01 you've got this! 😊

2023-01-16 20:22 UTC, TheCSharpAcademy commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
@kimfom01 Remember I made a video on this if you need help. But you should be able to do it on your own 😁https://www.youtube.com/watch?v=YUc5NZZVtjA&t=16s

2023-01-16 20:42 UTC, kimfom01 commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +        { "5 + 7", "12" },
I'll finish it after my TOEFL exams 😅

2023-01-18 22:57 UTC, TheCSharpAcademy requested changes

2023-01-18 22:57 UTC, TheCSharpAcademy commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +                numA = Random.Shared.Next(10, 100);
hey! we're almost there! sorry if the requirements were confusing, but you should only allow operations where the division results in a full number.  You need some sort of loop that will keep running if the equation is 27/6 for example. 
![image](https://user-images.githubusercontent.com/108711476/213313450-a1c45d8f-dc0c-4b2c-b5d2-21a27f12b35c.png)

2023-01-19 04:10 UTC, kimfom01 commented on kimfom01.Console.MathGame/MathGame/Controllers/GameController.cs
> +                numA = Random.Shared.Next(10, 100);
so sort of like the game shouldn't present questions that could lead to answers with decimal point right?

2023-01-20 01:26 UTC, merged