willN123: 1st submission for Math Game project.
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #169
Opened 2024-01-19 09:53 UTC by willN123

2024-01-22 23:17 UTC, edvaudin requested changes
Overall this is a good project with clean UI and codebase. I would suggest however that some of the methods are quite large in size and may do multiple things such as displaying options and processing them, when those are two separate behaviours. If you could particularly look at separating out the `GameScreen()` method, that will improve the readability of your code. Any questions, please let me know :)

2024-01-22 23:17 UTC, edvaudin commented on MathGame.willN123/Program.cs
> +}
This method should be split into several smaller methods since it has multiple side effects beyond displaying the Game Screen. For example it includes all the logic for selecting a random operation.

2024-01-22 23:17 UTC, edvaudin commented on MathGame.willN123/Program.cs
> +    }
This took a while for me to understand the purpose of this method. Can you find a way to refactor this to explain its purpose through code?

2024-01-23 14:03 UTC, edvaudin approved these changes
The changes look good to me! Well done!

2024-01-23 14:07 UTC, edvaudin requested changes
Sorry I didn't see this, but before this is approved, you need to fix the code analysis issues that have come up. The methods GetUserAnswer() and SetAnswerText() return values but those values are never used. I think you are simply setting global variables, in which case these methods should return void. Can you fix that and then we can get this project finished :)

2024-01-26 07:56 UTC, willN123 commented
Hi, sorry the issues should be fixed now and it shows that the code checks pass. Thanks for taking your time to do these reviews :)

2024-01-26 21:59 UTC, TheCSharpAcademy commented
@edvaudin is this good to go? 😁 Thanks for reviewing

2024-01-26 22:00 UTC, merged