Finished project
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #19
Opened 2023-02-27 06:06 UTC by LucianoNicolasArrieta

2023-03-01 19:40 UTC, TheCSharpAcademy commented
@kimfom01 @edvaudin @SinghxRaj Do any of you guys want to jump on this? You can assign yourself via the dashboard. If you pick it up, please follow this tutorial: https://thecsharpacademy.com/article/57

![image](https://user-images.githubusercontent.com/108711476/222246271-9b6885f5-5a1e-46a1-8cf5-7e6b038cf196.png)

2023-03-02 08:02 UTC, kimfom01 requested changes
Overall I love your game, Its fun and dynamic. A big well done for completing the extra challenges :clap: :clap: :smile: 
That being said, there are a few minor changes and points to think about. I need you to go through them and update the code before I can approve it as completed.

2023-03-02 08:02 UTC, kimfom01 commented on LucianoNicolasArrieta.MathGame/LucianoNicolasArrieta.MathGame/Program.cs
> +    protected int difficulty, numberOfQuestions, answeredQuestions, maxNumber, answerValue, score, correctAnswer, userAnswer;
Also I think you should use properties instead of fields here :smile: Check this post from [stack overflow](https://stackoverflow.com/questions/295104/what-is-the-difference-between-a-field-and-a-property)

2023-03-05 13:00 UTC, kimfom01 commented
Hey @LucianoNicolasArrieta don't forget to push your changes to so I can see them and merge the pull request 😅

2023-03-05 18:51 UTC, LucianoNicolasArrieta commented
> Hey @LucianoNicolasArrieta don't forget to push your changes to so I can see them and merge the pull request 😅

Yeah i just didn't finish everything yesterday 😅. I don't really know if i catch the properties thing, i made the change but i thought that you only need them when you have to access to the field from another class. Now i use setters and getters in internal methods of the class, is that right?

2023-03-06 05:43 UTC, kimfom01 commented
> > Hey @LucianoNicolasArrieta don't forget to push your changes to so I can see them and merge the pull request sweat_smile
> 
> Yeah i just didn't finish everything yesterday sweat_smile. I don't really know if i catch the properties thing, i made the change but i thought that you only need them when you have to access to the field from another class. Now i use setters and getters in internal methods of the class, is that right?

Well, yes and no :smiley: , the private can be left as fields while the public and protected as properties.
I am going to merge your PR now :grin:

2023-03-06 05:50 UTC, kimfom01 commented
One more thing I want you to note is that you can use methods to reduce the size of your switch statements as you have done on line 107. This will help reduce mistakes, repeating yourself and overall make your code more readable. Try to apply that on your next project :wink:

2023-03-06 05:52 UTC, merged