Game Finished
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #20
Opened 2023-02-27 20:02 UTC by Chad1082

2023-03-01 19:09 UTC, TheCSharpAcademy commented
@Chad1082 Hi Ian!! I saw that you are a member of the Academy but you haven't submitted your project on our dashboard. Could you please do that? 😊You can click on "Submit Project" as per screen shot: 

![image](https://user-images.githubusercontent.com/108711476/222240250-b4ea0729-e021-491e-977d-2f48b0d51cad.png)

2023-03-07 13:31 UTC, edvaudin requested changes
Hi @Chad1082! Well done for creating the Math Game; it ran well on my end without any crashses or breaking bugs.

Most of the comments I have provided are style related. Don't worry, they are fairly nitpicky comments and I have spoken with Pablo and we reckon that with use of tools built into Visual Studio, we can avoid a bunch of these. For example, have a look at the Code Cleanup tool in Visual Studio, which you can customise to your liking. The comments I entered are also in part to address what the Codacy analysis tool will likely be saying. You will need to get the all clear from that before we can merge. 

One overarching potential improvement that could be made is in the game engine class. What I notice is that each of the games do the following things in common:

- Create two random numbers
- Calculate a result
- Prompt the user for an answer
- Compare their answer with the result and add score if correct

The main thing that changes in each method is the operator, affecting the result and the question wording. I think a lot of this logic could be abstracted into separate methods. You could use something like an enum system for denoting the operator that will be used for any game, then you can get the expected results and question wording from there. It is possible that you could end up with one method called `StartGame(operator)` which just took in which operation was involved. If you have any questions about how to go about this, I am more than happy to have a chat either in DMs or in a Discord VC if either of those would be useful.

Overall, good job! As I am fairly new to formally reviewing these projects, please let me know if the feedback is useful and/or where I can improve; I appreciate that it is mostly style stuff, but that is normally a good sign!

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Menu.cs
> +
Remove unnecessary spacing.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Menu.cs
> +
Remove unnecessary spacing.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Menu.cs
> +
Remove unnecessary spacing.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Menu.cs
> +                    break;
Because of the `Console.Clear()` at line 22, I don't think this line ever gets displayed.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Helpers.cs
> +
Remove unnecessary usings.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Helpers.cs
> +namespace MathGame.chad1082
Convert to file-scoped namescape using VS refactoring tools.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Helpers.cs
> +        private static List<string> gameList = new List<string>();
We can shorten this as follows:

```suggestion
        private static List<string> gameList = new();
```

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Helpers.cs
> +
Remove uncessary space

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/Helpers.cs
> +        }
Suggested cleaner method here:

```suggestion
        internal static int[] GetDivisionNumbers()
        {
            var random = new Random();
            
            int firstNumber = random.Next(1, 100);
            int secondNumber = random.Next(1, 100);

            while (firstNumber % secondNumber != 0)
            {
                firstNumber = random.Next(1, 100);
                secondNumber = random.Next(1, 100);
            }

            var result = new int[2];

            result[0] = firstNumber;
            result[1] = secondNumber;
            
            return result;
        }
```

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/GameEngine.cs
> +
Remove unnecessary usings.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/GameEngine.cs
> +namespace MathGame.chad1082
Convert to file-scoped namespace using VS refactoring tool.

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/GameEngine.cs
> +
I think the need for a try catch block here can be removed by using `int.TryParse()` instead of `int.Parse()`. That way, you can just check in the if statement whether it parses into an int, if it does you can use the output, if not then you can tell them to answer with an integer.

_Please note that this feedback should apply to all other instances in the Game Engine. See if you can simplify the check using `int.TryParse()`._

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/GameEngine.cs
> +                            Console.WriteLine($"You answered {playerAnswer}, the correct was {correctAnswer}! Try Again!\nPress the enter key to continue");
Add word "answer" next to correct. _Please apply this in other occurrences_

```suggestion
                            Console.WriteLine($"You answered {playerAnswer}, the correct answer was {correctAnswer}! Try Again!\nPress the enter key to continue");
```

2023-03-07 13:31 UTC, edvaudin commented on MathGame.Chad1082/MathGame.Chad1082/GameEngine.cs
> +        }
Trimming some unnecessary spacing. _Please apply similar spacing for the rest of the class._

```suggestion
                } while (playerAnswer == "");
            }

            Helpers.AddGameScore(score, "Addition");

            Console.WriteLine($"You scored: {score} out of 4!");
            Console.WriteLine("Press Enter to return to the main menu.");
            Console.ReadLine();
        }
```

2023-03-09 17:09 UTC, Chad1082 commented
@edvaudin  Thank you for the feedback, it was very thorough and helpful!
I have made the changes you have suggested and had a go at refactoring the individual game logic using an enum in the latest commit. I think I have done it correctly! 
Thank you for your input!

2023-03-12 13:29 UTC, edvaudin approved these changes
Looks good to me! Well done and good look on your next projects!

2023-03-12 13:34 UTC, merged