Project by Mothnue
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #213
Opened 2024-03-27 17:37 UTC by Gincaza

Hello! That's my first time doing a PR, thank you so much for the tutorial!!

2024-03-27 20:09 UTC, VocalNight requested changes

2024-03-27 20:09 UTC, VocalNight commented on Math_Game.Mothnue/Program.cs
> +            int y = random.Next(1, diff);
Hey, good job on the project, everything looks good.

There's just one problem that you would need to fix, since it's a requirement.

Currently your division function is allowing any number to go through, which results in questions like these
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/12613508/a358d683-b8ce-43cf-b3c6-491f8c6aa4c8)

The division question in specific needs to generate only questions that can be answered by inputing an integer. We can't present to the user questions that would result in decimal number.

Could you you double check this part?

2024-03-28 14:32 UTC, Gincaza commented on Math_Game.Mothnue/Program.cs
> +            int y = random.Next(1, diff);
roger that

2024-03-28 17:55 UTC, VocalNight approved these changes
Everything good now!
Well done and good luck on your next projects!

2024-03-28 17:55 UTC, closed without merging