destocot math game ver01
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #22
Opened 2023-03-03 23:31 UTC by destocot

Hello, I attempted the first project Math Game,

I also did all the challenges. I know it is quite messy but I think everything works right. Would love any advice / feedback. 

destocot#0483 on discord

2023-03-03 23:58 UTC, edvaudin commented
Hi @destocot well done on submitting your first project. Before we get into reviewing it, try looking at the anaylsis feedback provided by Codacy. Make the recommended changes, then I will take a look :)

2023-03-04 02:02 UTC, edvaudin requested changes
@destocot Well done again on submitting your project, I am glad to say it worked well on my end with no errors or bugs that I could see. Well done also for cracking all of the challenges, excellent to see those all working. 

You have used a range of useful statements such as if elses and switches. The program is separated into separate classes and smaller methods which is good to see. However, I think we can clean this up by reducing the need for repeating code and extracting into lots more small methods and potentially other classes as well. This would reduce the need to change the code in multiple places if you wanted to modify the behaviour of a game or maybe change what a menu says.

In my comments, please note that a lot of them apply to multiple sections in the code such as repeating code sections, removing gaps in if else block, etc. So when you apply the feedback in one place, try seeing if you can apply it anywhere else. The refactoring tools in Visual Studio, particularly Extract Method will be your friend here - use it plentifully.

I hope this feedback helps! This is actually one of my first reviews so please let me know if any of it is unclear or if you have any questions in general.

2023-03-05 01:35 UTC, edvaudin commented
@destocot Hey, whilst you are working on changes, I saw that you are a member of the Academy but you haven't submitted your project on our dashboard. Could you please do that? 😊You can click on "Submit Project" as per screen shot:

![image](https://user-images.githubusercontent.com/2103197/222936828-3317cf03-09dc-4cdc-8cdf-1df475764687.png)

2023-03-05 06:25 UTC, destocot commented on MathGame.destocot/MathGame/Menu.cs
> +            }
I did attempt to do this part of the code, but I wasn't sure how to properly make it an object of its own.

2023-03-05 06:26 UTC, destocot commented on MathGame.destocot/MathGame/Menu.cs
> +        }
I enjoyed using the "extract method".  I tried to make more methods to help with making stuff more smaller and readable.

2023-03-05 06:34 UTC, destocot commented
The Codacy Review is incorrect, I fixed the issue it is asking for.

2023-03-05 22:05 UTC, TheCSharpAcademy commented
@edvaudin Looks like @destocot has submitted the link via dashboard. Could you please assign yourself to the issue ? 😊 You can find it clicking on "code reviews"  
![image](https://user-images.githubusercontent.com/108711476/222988547-29252f1f-eac7-459d-bd97-a77cad1c4974.png)

2023-03-05 22:15 UTC, edvaudin commented
> @edvaudin Looks like @destocot has submitted the link via dashboard. Could you please assign yourself to the issue ? 😊 You can find it clicking on "code reviews" in the left menu. ![image](https://user-images.githubusercontent.com/108711476/222988547-29252f1f-eac7-459d-bd97-a77cad1c4974.png)

Thanks for letting me know. I have assigned myself now. Cheers.

2023-03-06 01:20 UTC, edvaudin requested changes
This is looking much better than before. The menu class for example is elegant and to the point. There are just some `new` initialisations that can be simplified to `new()` and I want to ensure that the constant values used for difficulty modifiers (such as the *5 and the +1) are set only in one place each so that if they ever needed to change, this would only need to happen in one place.

For the style matters, if you haven't already tried it, give the Code Cleanup tool in Visual Studio a go. You can customise it to use certain rules to go through your code and apply them across all your classes. If you are interested, this is the setup I am currently using for mine - I am sure there is more I could add, but this is useful as a base:
![image](https://user-images.githubusercontent.com/2103197/222998791-22d8194d-3231-4847-9caa-38ce4eb33576.png)

2023-03-06 01:20 UTC, edvaudin commented on MathGame.destocot/MathGame/GameEngine.cs
> +        int[] divisionNumbers = Helpers.GetDivisionNumbers((int)diffModified * 5);
I notice that some constants are used to influence the difficulty modifiers, such as *5 for division and +1 for multiplication. These should really be class level consts so that if you need to change them, you only have to make one change in your code. Alternatively, since these numbers are always involving the difficulty modifier, perhaps a method to get the true modifier for each operation would be better.

2023-03-06 01:20 UTC, edvaudin commented on MathGame.destocot/MathGame/Helpers.cs
> +namespace MathGame
Change this to a file-scoped namespace. Remove the associated curly braces and add a semi-colon instead.

```suggestion
namespace MathGame;
```

2023-03-06 01:20 UTC, edvaudin commented on MathGame.destocot/MathGame/Helpers.cs
> +        internal static List<Game> games = new List<Game>();
This initialisation can be simplified to:

```suggestion
        internal static List<Game> games = new();
```

2023-03-06 01:20 UTC, edvaudin commented on MathGame.destocot/MathGame/Helpers.cs
> +        internal static int DisplayProblems(int score, int num1, int num2, string operatorSymbol, Func<int, int, int> operation)
As this method also hosts the processing of a user's answer as well as displaying the problems, the following may be a more appropriate name:
```suggestion
        internal static int ProcessProblems(int score, int num1, int num2, string operatorSymbol, Func<int, int, int> operation)
```

2023-03-06 01:20 UTC, edvaudin commented on MathGame.destocot/MathGame/Helpers.cs
> +                Console.WriteLine("Incorrect!\n");
I would personally use curly braces here since you are using them for the if block. Best to be consistent.

2023-03-20 18:46 UTC, edvaudin commented
Hi @destocot hope you are well. Just wondering if you have had a chance to look over my latest feedback? Please let me know if there are any issues or if you have any questions, I'd be happy to help!

2023-05-07 22:28 UTC, TheCSharpAcademy commented
@destocot Hello! Where have you been? 😁

2023-05-22 04:03 UTC, destocot commented
> @destocot Hello! Where have you been? 😁

sorry, and thank you for the checkup. I really enjoyed working with this program, but I enrolled in a more structured bootcamp hopefully it was the right decision.

2023-05-22 04:03 UTC, closed without merging