completed the math game
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #266
Opened 2024-06-21 15:26 UTC by ukpagrace

Implemented the base requirements 
Also added the extra requirements

2024-06-22 11:14 UTC, TheCSharpAcademy requested changes
@ukpagrace Well done! The project works great! It has all the requirements 🤓✅

I'm going to request changes due to the significant amount of violations of our code styling guides. I know it's a bit annoying, but this will put you in a good path for the next projects. 😊. You can find more about our code conventions here. https://www.thecsharpacademy.com/article/58/code-conventions

You can use the cleanup button to fix indentation (I'm assuming you come from a JS/Python background?), as per picture: 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/55cc406b-9785-4e6b-82f6-aa2349a3a8e3)

Also consider using Console.Clear() after certain actions for better UX. It gets messy really quickly: 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/c72d11ac-a864-4e7a-8d28-5057af783821)

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
Please remove unused code, including comments.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +
Please remove unnecessary empty lines.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +
Unnecessary empty line.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +
Unnecessary empty line.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +
Several instances of unnecessary empty lines, I'll let you find the other ones 😊

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +    Console.WriteLine(Option);
As per C# conventions, indentation should be 4 spaces.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +          case "y":
Indentation of case "y" doesn't match the other cases

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +void MultiplicationGame(){
This isn't a requirement but it would be a good exercise in DRY (Don't Repeat Yourself) to have one method for all games.

2024-06-22 11:14 UTC, TheCSharpAcademy commented on MathGame.ukpagrace/Program.cs
> +  Random random= new Random();
To avoid repetition you can instantiate objects like this MyClass myObject = new();

2024-06-23 12:06 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +
noted

2024-06-23 12:06 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +    Console.WriteLine(Option);
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +  Random random= new Random();
noted

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +void MultiplicationGame(){
noted, thanks

2024-06-23 12:07 UTC, ukpagrace commented on MathGame.ukpagrace/Program.cs
> +          case "y":
noted

2024-06-29 01:23 UTC, TheCSharpAcademy commented
@ukpagrace It's much better now, well done!  Looking forward to the next one! 😁

2024-06-29 01:23 UTC, closed without merging