MathGame submission
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #270
Opened 2024-06-25 17:38 UTC by CBoton

2024-06-26 14:45 UTC, stevietv commented
Hi @CBoton - thanks for your first project submission! I've taken a look over it and for now it needs a bit of work. I'm missing the MathGame.Models folder where your definition of Game is stored. Can you take a look?

One additional feedback: 
Make sure to submit your next projects within a subfolder, like `MathGame.CBoton` instead of files directly in the top directory.

2024-06-27 01:32 UTC, CBoton commented
Hi Stevie,

I have added the Models folder and Game.Cs file.

I will make sure to add the entire folder next time.

Thanks,
Curtis

On Wed, Jun 26, 2024 at 7:45 AM Stevie Robinson ***@***.***>
wrote:

> Hi @CBoton <https://github.com/CBoton> - thanks for your first project
> submission! I've taken a look over it and for now it needs a bit of work.
> I'm missing the MathGame.Models folder where your definition of Game is
> stored. Can you take a look?
>
> One additional feedback:
> Make sure to submit your next projects within a subfolder, like
> MathGame.CBoton instead of files directly in the top directory.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/270#issuecomment-2191895697>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWGPBVN37RRKRZVI5US2WDZJLH2NAVCNFSM6AAAAABJ4J4G36VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJRHA4TKNRZG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-06-29 09:03 UTC, stevietv commented
hi @CBoton - your models folder currently has a trailing space:
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/1117625/71263b8c-cd07-4bb6-b60c-fb6536253726)

this makes it impossible to checkout in windows as its an invalid path:
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/1117625/69c0c338-02ef-4cb4-b8da-76b9fdd6c6d2)


can you fix that path and re-push?

2024-06-29 14:36 UTC, stevietv requested changes

2024-06-29 14:36 UTC, stevietv commented on GameEngine.cs
> +using static System.Formats.Asn1.AsnWriter;
unnecessary using - this library isn't being used

2024-06-29 14:36 UTC, stevietv commented on GameEngine.cs
> +using System;
unnecessary using - this is implicitly used, no need to add.

2024-06-29 14:36 UTC, stevietv commented on Program.cs
> +using Microsoft.VisualBasic;
unnecessary using - this library isn't being used

2024-06-29 14:37 UTC, stevietv commented
Hi @CBoton - great work, the progam does indeed what it needs to do, thanks for the submission!
In order to mark it as approved there are few tweaks to make to keep with the required code conventions.

2024-06-29 14:59 UTC, CBoton commented
Hi Stevie,

I removed the using statements.

Thanks

On Sat, Jun 29, 2024, 7:37 AM Stevie Robinson ***@***.***>
wrote:

> Hi @CBoton <https://github.com/CBoton> - great work, the progam does
> indeed what it needs to do, thanks for the submission!
> In order to mark it as approved there are few tweaks to make to keep with
> the required code conventions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/270#issuecomment-2198216155>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWGPBUGWMPJRZZ7NX32CZLZJ3BCFAVCNFSM6AAAAABJ4J4G36VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJYGIYTMMJVGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-06-29 16:17 UTC, stevietv commented
you can't remove all 4 from GameEngine.cs - only the two I commented.
Its important to test your code once you edit it, right now the program won't run again.

2024-06-29 16:37 UTC, CBoton commented
Sorry Stevie, I'm on the road and just updated from my phone on GitHub so
couldn't test.

On Sat, Jun 29, 2024, 9:18 AM Stevie Robinson ***@***.***>
wrote:

> you can't remove all 4 from GameEngine.cs - only the two I commented.
> Its important to test your code once you edit it, right now the program
> won't run again.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/270#issuecomment-2198249503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWGPBS5DHBSCWDWWXZYWZTZJ3M4PAVCNFSM6AAAAABJ4J4G36VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJYGI2DSNJQGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-06-29 16:45 UTC, stevietv commented
No worries, update it properly once youre around again and then we'll approve it :)

2024-07-02 17:24 UTC, CBoton commented
Hi Stevie,

I think it's good now.

Thanks,
Curtis

On Sat, Jun 29, 2024 at 9:46 AM Stevie Robinson ***@***.***>
wrote:

> No worries, update it properly once youre around again and then we'll
> approve it :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/270#issuecomment-2198257921>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWGPBSAOQOMXVQX2K3UWHDZJ3QETAVCNFSM6AAAAABJ4J4G36VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJYGI2TOOJSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> .com>
>

2024-07-02 19:56 UTC, stevietv commented
thanks for working with me to finalise it! its all approved now! ✅

2024-07-02 19:56 UTC, closed without merging