Mathgame
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #281
Opened 2024-07-06 12:18 UTC by mrmyxc

2024-07-06 17:11 UTC, javedkhan2k2 requested changes
@mrmyxc a job well done.
Please review the comments and fix the issue with Number of rounds when the user set it to negative values.
Don't forget to commit.

2024-07-06 17:11 UTC, javedkhan2k2 commented on csa-maths-game/csa-maths-game/Game.cs
> +                success = Int32.TryParse(Console.ReadLine(), out response);
I can set response to 0 and negative values. When I set the number of rounds to -5, I could not able to play the game anymore.
Kindly add the validation so that the number of rounds should be greater than 0.

2024-07-06 17:11 UTC, javedkhan2k2 commented on csa-maths-game/csa-maths-game/Game.cs
> +            while (correctAnswer && score < NumberOfRounds)
Can you change the logic so the game is not quit when the User give a wrong answer.
This is also A valid game but this was a requirement that user need to answer predefined number (in your case it is max int) questions and in challenge one of the part was to make it dynamic (which is already implemented).

2024-07-06 17:11 UTC, javedkhan2k2 commented on csa-maths-game/csa-maths-game/Division.cs
> +            if (operandA == 0 || operandB == 0) return false;
when operandA has 0 value, it is a valid mathematical operation. You can change it or leave it.

2024-07-06 17:53 UTC, mrmyxc commented on csa-maths-game/csa-maths-game/Game.cs
> +                success = Int32.TryParse(Console.ReadLine(), out response);
thanks, done

2024-07-06 17:54 UTC, mrmyxc commented on csa-maths-game/csa-maths-game/Game.cs
> +            while (correctAnswer && score < NumberOfRounds)
I didn't see this requirement to answer a predetermined number of questions. 
Was it in the tutorial video? because I didn't watch it

2024-07-07 07:22 UTC, javedkhan2k2 commented
@mrmyxc Approved. Brilliant work.
I will only suggest to convert part of your code to classes as well e.g.
`static List<(int score, string name)> highScores = new List<(int score, string name)>(MaxScores); `
define a class
`static List<GameScore> highScores = new List<GameScore>(MaxScores);`
Good luck with your next Project.

2024-07-07 07:22 UTC, closed without merging