First commit
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #34
Opened 2023-04-01 04:53 UTC by kirielss

2023-04-05 05:25 UTC, TheCSharpAcademy requested changes
Your project is looking great! And you were very close to completing it. Let me know if you have questions about my comments.

2023-04-05 05:25 UTC, TheCSharpAcademy commented on MathGame.kirielss/MathGame.kirielss/Game.cs
> +                case 4:
![image](https://user-images.githubusercontent.com/108711476/229987875-e2da415f-0011-496d-a095-c68bd7eaff12.png)

Hey there! As per requirements, you shouldn't allow your division to result in a split number. You have to create a loop that keeps running until the remainder between the two random numbers = 0. Hope that makes sense?

2023-04-05 05:25 UTC, TheCSharpAcademy commented on MathGame.kirielss/MathGame.kirielss/Game.cs
> +
Please remove unnecessary empty lines, as per [code conventions](https://www.thecsharpacademy.com/article/58).

2023-04-05 05:25 UTC, TheCSharpAcademy commented on MathGame.kirielss/MathGame.kirielss/Game.cs
> +﻿using System;
Please remove unused 'usings' as per code conventions:

![image](https://user-images.githubusercontent.com/108711476/229988273-4d42d11f-25a4-48a9-88de-f43ada81ff59.png)

2023-04-05 05:30 UTC, TheCSharpAcademy commented
@kirielss Could you please submit the link to your project on the dashboard (or project page?), I saw that you submitted the calculator, but couldn't find a record for the math game.

2023-04-05 22:53 UTC, TheCSharpAcademy commented
> hey! this link? https://github.com/kirielss/CodeReviews.Console.MathGame/tree/main/MathGame.kirielss

yes please

2023-04-05 23:29 UTC, TheCSharpAcademy commented
> hey! this link? https://github.com/kirielss/CodeReviews.Console.MathGame/tree/main/MathGame.kirielss

Actually, I think you had already submitted? I think I had mistakenly marked it as complete (or something else weird happened), but the project is marked as under review now. I'll mark it as complete as soon as you work on the requested changes 😁

2023-04-17 00:08 UTC, TheCSharpAcademy commented
@kirielss Hey there! Just checking how you're going with the project. Do you have questions about the changes requested? 😊

2023-04-17 13:48 UTC, kirielss commented
Yeah, i didn't get how you want the division. Can you give some input/output examples?

2023-04-20 01:17 UTC, TheCSharpAcademy commented
> Yeah, i didn't get how you want the division. Can you give some input/output examples?
> 
> So it is supposed to run a loop until % 2 == 0, but should the user keep providing answers till the loop is done? (sorry, I tried to create it without watching the video tutorial)

No, the program should generate 2 numbers in the background until it finds numbers that will result in an integer. Then the equation will be presented to the user. 😃

2023-05-03 01:10 UTC, TheCSharpAcademy commented
@kirielss Let me know if you need help! 😊

2023-05-25 21:01 UTC, TheCSharpAcademy commented
@kirielss  I'm closing the PR for admin purposes but feel free to reopen it if you want to work on the project.

2023-05-25 21:01 UTC, closed without merging