Simon's math game
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #39
Opened 2023-04-07 10:59 UTC by Simon9566

Looks to be fine unless I created a bug after the last test :)

2023-04-11 00:43 UTC, TheCSharpAcademy requested changes
Hey there! It's looking great! Good work so far! Please have a look at the two comments I made in the review and also make sure the program only presents to the user divisions that result in integers, as per the project's requirements. 

Oh, also as per requirements I need to have an option to see a list of previous games played. Let me know if you need help! You can also see how it's done in this course: https://www.youtube.com/watch?v=iLByqqLGYEc&lc=Ugzhol3KJJuXmjd86Id4AaABAg

![image](https://user-images.githubusercontent.com/108711476/231026137-2259ceb1-56ba-433e-a12b-bba5c016eff1.png)

2023-04-11 00:43 UTC, TheCSharpAcademy commented on Simon9566_Math_game/Program.cs
> +difficulties.Add("S", "special");
At the moment for whatever reason when I play a game, I get only one operation. Example: 
![image](https://user-images.githubusercontent.com/108711476/231025738-79e26e1e-c313-4b87-abd7-a397d89c3b40.png).

You can either let me choose which operation I want or make it random so it alternates

2023-04-11 00:43 UTC, TheCSharpAcademy commented on Simon9566_Math_game/Program.cs
> +    guess = Convert.ToInt32(Console.ReadLine());
At the moment there's no validation so if I input something that can't be parsed I get an error. You can create a loop that keeps running while the attempt is invalid. Let me know if you need help. 

![image](https://user-images.githubusercontent.com/108711476/231025894-eb4dbb79-ae75-4ce3-b8fb-081697fa3ac3.png)

2023-04-13 09:39 UTC, TheCSharpAcademy requested changes
Hey! You were doing well! But now you transformed the app in a simple calculator 😟

This is the behavior I expect: Upon choosing an operation I get given questions that I have to answer. You can let me choose how many questions or have a fixed number (up to you). 

The history can consist of date, game type and number of correct answers. Let me know if you need help!

2023-04-13 10:24 UTC, Simon9566 commented
Wait it changed THIS pull request?
I wanted to open a new one with the calculator app I guess I messed up
somewhere with pushing the changes, I'll try to fix it later

On Thu, Apr 13, 2023 at 11:39 AM The C# Academy ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey! You were doing well! But now you transformed the app in a simple
> calculator 😟
>
> This is the behavior I expect: Upon choosing an operation I get given
> questions that I have to answer. You can let me choose how many questions
> or have a fixed number (up to you).
>
> The history can consist of date, game type and number of correct answers.
> Let me know if you need help!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/39#pullrequestreview-1383043124>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5O3M2SJESA2S22PZEEBEFDXA7CWHANCNFSM6AAAAAAWWOQN6A>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2023-04-20 01:16 UTC, TheCSharpAcademy commented
@Simon9566 hey there! Just stopping by to see if you need any help. 😁

2023-04-20 23:01 UTC, TheCSharpAcademy requested changes
Hi there! At the moment your project doesn't compile. There are several errors, such as void methods trying to return something. 

![image](https://user-images.githubusercontent.com/108711476/233504373-9b8a5be6-f7ae-4df3-8da9-371331114954.png)

2023-04-21 09:41 UTC, Simon9566 commented
Visual studio refused to push the commit that fixes those and i went to
sleep due to my time zone :)

On Fri, Apr 21, 2023 at 1:01 AM The C# Academy ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi there! At the moment your project doesn't compile. There are several
> errors, such as void methods trying to return something.
>
> [image: image]
> <https://user-images.githubusercontent.com/108711476/233504373-9b8a5be6-f7ae-4df3-8da9-371331114954.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/pull/39#pullrequestreview-1394861318>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5O3M2QWM3ODXR4CNB7C22TXCG54DANCNFSM6AAAAAAWWOQN6A>
> .
> You are receiving this because you were mentioned.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.MathGame/pull/39/review/1394861318@
> github.com>
>

2023-04-21 20:18 UTC, TheCSharpAcademy requested changes
Good stuff! You're close! I'm usually not super strict with the first project except for the requirements. The users should only be presented with divisions that RESULT IN AN INTEGER, as per requirement 2. 

![image](https://user-images.githubusercontent.com/108711476/233727134-f849ef51-71e9-41de-9862-593916c61ec1.png)

2023-04-23 23:01 UTC, TheCSharpAcademy requested changes

2023-04-23 23:01 UTC, TheCSharpAcademy commented on Simon9566_Math_game/Program.cs
> -    result = $"{a} / {b} = {a / b}";
Hey! I'm sorry, I think you still didn't understand. I know it's a bit frustrating, and you just want to finish the project, but I cant let this requirement pass. So let me explain again: At the moment your program presents to the users equations that result in non-integers. Example: 
![image](https://user-images.githubusercontent.com/108711476/233870763-b302e9ab-c3a8-437d-9f0f-dc5b96d713f8.png). 

This shouldn't happen. This equation should never be shown to the users. Another example: 9/4 shouldn't be allowed, 9/3 should. You can use a loop to keep generating numbers until you get a suitable equation. Let me know if that makes sense?

2023-04-24 07:07 UTC, Simon9566 commented on Simon9566_Math_game/Program.cs
> -    result = $"{a} / {b} = {a / b}";
Ah so it should only roll divisions that have a result a % b == 0. You are absolutely right I did misunderstand that part :)

2023-04-24 21:49 UTC, merged