Completed Game
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #44
Opened 2023-04-16 23:34 UTC by barakisbrown

2023-04-16 23:53 UTC, TheCSharpAcademy requested changes
Hi there! The project looks great. The game does everything it's supposed to do and I like how you used inheritance 😁 It's also very clean and tidy. 

Could you please just fix the division issue so I can approve it?

2023-04-16 23:53 UTC, TheCSharpAcademy commented on MathGame.barakisbrown/MathGame.barakisbrown/Problems/Division.cs
> +internal class Division : IProblem
The division game should only have questions that result in integers, as per the 2nd requirement. Let me know if you need help solving it. 

![image](https://user-images.githubusercontent.com/108711476/232350514-51f23746-0b61-4a1d-85d6-f709ba275abc.png)

2023-04-17 00:13 UTC, barakisbrown commented on MathGame.barakisbrown/MathGame.barakisbrown/Problems/Division.cs
> +internal class Division : IProblem
Division issue has been resolved.

2023-04-20 01:14 UTC, TheCSharpAcademy commented
@barakisbrown Hi there! Just checking if you need any help committing your updates? 😁

2023-04-20 01:21 UTC, barakisbrown commented
I did do the commits that you asked about.  I told you in discord that I have closed it saying it was completed.

2023-04-20 03:19 UTC, barakisbrown commented
DOH .. I forgot to push what I had done.  Now it is finished

2023-04-20 06:07 UTC, TheCSharpAcademy requested changes
Hey! The issue persists. You can't allow your program to show to the users equations that result in non-integers. Let me know you if you need help 🤓

2023-04-20 06:22 UTC, barakisbrown commented
I have fixed the issue by looping until the two numbers give me an integer.

2023-04-20 06:23 UTC, merged