Code review for MathGame
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #5
Opened 2023-01-22 09:50 UTC by SinghxRaj

2023-01-22 23:18 UTC, TheCSharpAcademy requested changes

2023-01-22 23:18 UTC, TheCSharpAcademy commented on SinghxRaj.MathGame/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
Please remove comment

2023-01-22 23:18 UTC, TheCSharpAcademy commented on SinghxRaj.MathGame/Option.cs
> +using System.Threading.Tasks;
Please remove unused usings

2023-01-22 23:18 UTC, TheCSharpAcademy commented on SinghxRaj.MathGame/MathGameHistory.cs
> +﻿namespace SinghxRaj.MathGame.MathGame;
please add space between namespace and class name

2023-01-22 23:18 UTC, TheCSharpAcademy commented on SinghxRaj.MathGame/Program.cs
> +
Please reinstate deleted project folders from repository

2023-01-22 23:58 UTC, SinghxRaj commented on SinghxRaj.MathGame/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
Removed the comments

2023-01-22 23:59 UTC, SinghxRaj commented on SinghxRaj.MathGame/MathGameHistory.cs
> +﻿namespace SinghxRaj.MathGame.MathGame;
Added space between the namespace and class name. I'll be make sure to keep doing this moving forward.

2023-01-23 00:00 UTC, SinghxRaj commented on SinghxRaj.MathGame/Program.cs
> +
I ended up cherry picking the commit when I first forked the repo and merged it into HEAD.

2023-01-23 00:00 UTC, SinghxRaj commented on SinghxRaj.MathGame/Option.cs
> +using System.Threading.Tasks;
Removed all the unnecessary using directives.

2023-01-23 05:52 UTC, merged