finished up MathGame
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #6
Opened 2023-01-22 21:46 UTC by S-Smans

Finished the project before I forked it. I just renamed the folder and copied it on the cloned repository.

2023-01-22 23:55 UTC, TheCSharpAcademy requested changes

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Helper.cs
> +    // Difficulty level of the game
I strongly recommend you name your variables so you don't have to explain them with comments. If your variable  was called DifficultyLevel, for example, you code exclude the comment. Code should be self-explanatory and comments should only be added when absolutely necessary.

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Helper.cs
> +    // Question amount that are being asked
Please name your variable in a way that the comment isn't necessary.

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Helper.cs
> +    // Create a class that returns 2 random numbers in an array
Unnecessary comment (the method's name explains enough)

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Helper.cs
> +
Remove unnecessary empty lines 102,103. As a rule of thumb, have spaces between methods, between groups of statements (such as line 89), between namespaces and classes,  but not between curly brackets

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Helper.cs
> +﻿
remove empty line 1

2023-01-22 23:55 UTC, TheCSharpAcademy commented on MathGame.S-Smans/MathGame/Game.cs
> +﻿
Remove empty line 1

2023-01-23 00:48 UTC, S-Smans commented on MathGame.S-Smans/MathGame/Helper.cs
> +    // Difficulty level of the game
Renamed the public fields in the Pascal case.

2023-01-23 00:51 UTC, S-Smans commented on MathGame.S-Smans/MathGame/Helper.cs
> +
Went through my source code and added/removed spacing following specified rules

2023-01-23 00:55 UTC, S-Smans commented
Do I need to press the re-request after I implemented my changes?

2023-01-23 04:39 UTC, merged