MathGame
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #62
Opened 2023-06-08 11:41 UTC by InfiniteBlanK3T

2023-06-20 01:29 UTC, TheCSharpAcademy commented
@InfiniteBlanK3T Hi there! I can't see this project submitted in The C# Academy platform. Could you please do that so I can review it? 😊

2023-06-22 09:32 UTC, InfiniteBlanK3T commented
Submitted!

2023-06-22 23:09 UTC, TheCSharpAcademy requested changes

2023-06-22 23:09 UTC, TheCSharpAcademy commented on InfiniteBlanK3T.MathGame/Program.cs
> +    {
This division shouldn't be presented to the user, since it results in a non-integer: 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/12049476-0ed7-446a-b372-b25bd30e78f1)

2023-07-07 22:55 UTC, TheCSharpAcademy commented
@InfiniteBlanK3T Let me know if you need any help?

2023-07-28 00:10 UTC, TheCSharpAcademy commented
@InfiniteBlanK3T We haven't heard from you in a while 😔

2023-08-05 11:22 UTC, TheCSharpAcademy commented
@InfiniteBlanK3T I'm closing the PR as it's been reviewed more than a month ago, feel free to resubmit the project and reopen the PR if you'd like to proceed.

2023-08-05 11:22 UTC, closed without merging