project completed
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #66
Opened 2023-06-17 12:31 UTC by CosmicPhoenix2029

2023-06-20 01:16 UTC, TheCSharpAcademy reviewed
Hi there! Good work! The project looks great. I'll just ask you to review your division logic, as per Requirement 2: 

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/271bb006-cfa0-4b59-a8af-7750750b599f)

2023-06-20 01:16 UTC, TheCSharpAcademy commented on MathGame.CosmicPhoenix2029/GameItem.cs
> +            case "D":
Divisions that result in non-integers shouldn't be presented to the user.

2023-06-22 23:03 UTC, TheCSharpAcademy requested changes

2023-06-22 23:03 UTC, TheCSharpAcademy commented on MathGame.CosmicPhoenix2029/GameItem.cs
> +                Question = $"Rounded down to the nearest whole number, what is {NumOne} / {NumTwo} / {NumThree} / {NumFour}";
Just to clarify, your program should never show this equation to the user, since it doesn't result in a whole number. Every division presented to the user needs to result in an integer. Let me know if that makes sense?
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/884643e4-ce72-41a9-b6de-ff44926060c0)

2023-06-24 16:10 UTC, CosmicPhoenix2029 commented
Hi, many thanks for the review. I believe I understand the requirement now. I will make the requested changes. 
As I want this to be unique, I want to keep the logic for having an increased number per difficulty. This makes it so that the logic for division is not process efficient at all, however believe for uniqueness, it is worth keeping in. 

In order to improve the process efficiency when the division case is matched, I have tried to min max the random numbers to give it the best chance of being a whole number, without having to iterate, yet I'm no mathematician and so am aware there will always be room to improve the efficiency.

2023-06-24 23:40 UTC, TheCSharpAcademy commented
@CosmicPhoenix2029 No problem, as long as questions presented to the user can only result in integers. 😊

2023-06-25 10:05 UTC, CosmicPhoenix2029 commented
Hi - I have amended the division logic so instead of increasing the number of numbers for each difficulty, the 2nd divisor will be in a specific range per difficulty. For Easy mode, the divisor is between 1 and 5, Medium mode is between 6 and 15, and hard is between 16 and 100. I did try to work with the logic previously implemented, however was running into too many issues. Really appreciate your reviews on this project, it helps me a lot.

2023-06-26 01:12 UTC, TheCSharpAcademy commented
@CosmicPhoenix2029 Well done! I'm approving the project. I'm not overly strict with comments in the first couple of projects, but for the future, please have a look at Item 3 in this article: https://thecsharpacademy.com/article/58. 

It's ok to comment on code when studying, but when pushing it, make sure you comment only when absolutely necessary 😊. Code littered with redundant comments is heavily frowned upon. 

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/9f80209b-95b3-4afe-b507-4a2a0d679575)

2023-06-26 01:13 UTC, merged