project finished
TheCSharpAcademy/CodeReviews.Console.MathGame pull request #97
Opened 2023-09-01 11:40 UTC by Aapje185

2023-09-04 00:34 UTC, TheCSharpAcademy requested changes
@Aapje185 Thanks for submitting! It's looking great. Could you please just fix the issue in the comment? 😊

2023-09-04 00:34 UTC, TheCSharpAcademy commented on MathGame.Aapje185/UI/UserInterface.cs
> +        if (userChoice == 5) return;
I'm getting this error when I choose division 

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/dc7b9883-74cf-4a42-ac6b-20c9b9bf63de)

2023-09-04 16:12 UTC, Aapje185 commented on MathGame.Aapje185/UI/UserInterface.cs
> +        if (userChoice == 5) return;
Thank you for reviewing. Bug should be fixed now.

2023-09-05 01:37 UTC, TheCSharpAcademy requested changes
@Aapje185 almost there! As per second requirement, you shouldn't show equations that result in non-integers: 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/ab79279a-e95f-43c3-b2ea-7e2174e4607f)

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.MathGame/assets/108711476/41d72bcd-82b1-4397-9d7d-3f129d51d4f0)

2023-09-15 05:52 UTC, TheCSharpAcademy commented
@Aapje185 I'm closing the PR as it's been 2 weeks, but feel free to reopen it if you want to continue 😊

2023-09-15 05:52 UTC, closed without merging